name: Deployment
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: Cache Cypress Binary
        id: cache-cypress-binary
        uses: actions/cache@v2
        with:
          path: cypress/cache
          key: cypress-binary-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache-cypress-binary.outputs.cache-hit != 'true'
        run: cypress install
        
      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.2"
      - name: Run test
        run: npm run test
      - name: Run e2e
        run: npm run e2e

  deploy-bff:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_BFF_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

  deploy-client:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_CLIENT_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
