name: deploy-bff
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "16.13.2"
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm run test
      - name: Run e2e test
        run: npm run e2e

  deploy-bff:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_BFF_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

  deploy-client:
    runs-on: ubuntu-latest
    needs: [deploy-bff]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_CLIENT_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
